# Generated by Django 5.2.3 on 2025-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='cashout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('low_hold', 'Low Hold'), ('arb', 'Arbitrage'), ('middle', 'Middle'), ('positive_ev', 'Positive EV'), ('future', 'Future')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bet',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('american_football', 'Am.Football'), ('ice_hockey', 'Ice Hockey'), ('baseball', 'Baseball'), ('tennis', 'Tennis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bet',
            name='sportsbook',
            field=models.CharField(choices=[('skybook', 'Skybook'), ('bovada', 'Bovada'), ('betmania', 'BetMania'), ('matchbook', 'Matchbook'), ('sbgglobal', 'SBGGlobal'), ('5dimes_ca', '5Dimes.ca'), ('sportsbetting', 'SportsBetting'), ('betonline', 'BetOnline'), ('pinnacle', 'Pinnacle'), ('justbet', 'JustBet'), ('jazz', 'Jazz'), ('heritage', 'Heritage'), ('bethorizon', 'BetHorizon'), ('public_percent', 'Public%'), ('sportbet', 'SportBet'), ('caribsports', 'CaribSports'), ('catalina', 'Catalina'), ('grande', 'Grande'), ('buckeye', 'Buckeye'), ('iasports', 'IASports'), ('intertops', 'Intertops'), ('mirage', 'Mirage'), ('westgate', 'Westgate'), ('betphoenix', 'BetPhoenix'), ('payperhead', 'PayPerHead'), ('betqs', 'BetQS'), ('easyst', 'EasySt'), ('southpoint', 'SouthPoint'), ('5dimes_reduced', '5DimesReduced'), ('williamhill', 'William Hill'), ('wwwager', 'WWWager'), ('sportsinteraction', 'SportsInterAction'), ('betus', 'BetUS'), ('peppermill', 'Peppermill'), ('computer', 'Computer'), ('youwager', 'YouWager'), ('coasts', 'Coasts'), ('stations', 'Stations'), ('caesars', 'Caesars'), ('wynn', 'Wynn'), ('jerrys', 'Jerrys'), ('click_and_bet', 'Click and Bet'), ('atlantis', 'Atlantis'), ('abc', 'ABC'), ('stratosphere', 'Stratosphere'), ('wagerweb', 'WagerWeb'), ('test2', 'Test2'), ('ticosports', 'TicoSports'), ('perhead', 'PerHead'), ('golden_nugget', 'Golden Nugget'), ('wagerabc', 'WagerABC'), ('bookie', 'Bookie'), ('playcr', 'PlayCR'), ('topbet', 'TopBet'), ('betosb', 'BetOSB'), ('cd_sports', 'CD Sports'), ('odds', 'Odds'), ('wagerperhead', 'WagerPerHead'), ('lowvig', 'Lowvig'), ('betsts', 'BetSTS'), ('linepros', 'LinePros'), ('bpph', 'BPPH'), ('evo', 'EVO'), ('treasure_island', 'Treasure Island'), ('carson_valley_inn', 'Carson Valley Inn'), ('7pph', '7PPH'), ('cg_technology', 'CG Technology'), ('wagermadness', 'WagerMadness'), ('casablanca', 'CasaBlanca'), ('bethk', 'BETHK'), ('heritage105', 'Heritage105'), ('lovbet', 'Lovbet'), ('bet365', 'Bet365'), ('looselines', 'LooseLines'), ('mybookie', 'MyBookie'), ('ucabet', 'UCABet'), ('mgm', 'MGM'), ('el_caribe', 'El Caribe'), ('gtbets', 'GTbets'), ('betdsi', 'BetDSI'), ('sports411', 'Sports411'), ('acepph', 'AcePPH'), ('actionpass', 'ActionPass'), ('bet33', 'Bet33'), ('betfair', 'BetFair'), ('betisn', 'BetISN'), ('betway', 'BetWay'), ('codere', 'Codere'), ('consensus', 'Consensus'), ('dollar', 'Dollar'), ('hotelnv', 'HotelNV'), ('isi_sports', 'ISI Sports'), ('lakeside_inn', 'Lakeside Inn'), ('osc', 'OSC'), ('premier', 'Premier'), ('probets', 'ProBets'), ('samvo', 'Samvo'), ('betanysports', 'BetAnySports'), ('sportsbetting_au', 'SportsBetting AU'), ('sportsbetting_ol', 'SportsBetting OL'), ('baldinis', 'Baldinis'), ('betcris', 'BetCRIS'), ('dimebet', 'DimeBet'), ('delottery', 'DELottery'), ('williamhill_nj', 'William Hill NJ'), ('bteast', 'BetEast'), ('williamhill_ms', 'William Hill MS'), ('draftkings', 'DraftKings'), ('santaana', 'SantaAna'), ('scarlet_pearl', 'Scarlet Pearl'), ('rhode_island_lottery', 'Rhode Island Lottery'), ('betlucky_wi', 'BetLucky-WI'), ('betlucky_mg', 'BetLucky-MG'), ('playmgm', 'PlayMGM'), ('moneyball', 'Moneyball'), ('buffalo_thunder', 'Buffalo Thunder'), ('circa', 'Circa'), ('betworks', 'BetWorks'), ('isleta', 'Isleta'), ('pearl_river', 'Pearl River'), ('chinook', 'Chinook'), ('rwcatskills', 'RWCatskills'), ('route66', 'Route66'), ('thescore', 'TheScore'), ('beau_rivage', 'Beau Rivage'), ('monarch_bh', 'Monarch BH'), ('sky_ute', 'Sky Ute'), ('parx', 'Parx'), ('wmhill', 'WMHill'), ('betmgmdetroit', 'BetMGMDetroit'), ('spiritmountain', 'SpiritMountain'), ('bet105', 'Bet105'), ('sasquatchwildcardco', 'SasquatchWildCardCO'), ('maverick', 'Maverick'), ('betsson', 'Betsson'), ('odawa', 'Odawa'), ('firebet', 'FireBet'), ('sugarhouse', 'SugarHouse'), ('betrivers', 'BetRivers'), ('consensus_us', 'Consensus US'), ('ballybet', 'BallyBet'), ('resortworldlv', 'ResortWorldLV'), ('lines_ag', 'Lines.ag'), ('gila_river_az', 'Gila River AZ'), ('cadillac_jacks_sd', 'Cadillac Jacks SD'), ('tin_lizzie_sd', 'Tin Lizzie SD'), ('emerald_queen_wa', 'Emerald Queen WA'), ('circaia', 'CircaIA'), ('elysdc', 'ELYSDC'), ('boyd', 'Boyd'), ('betkota', 'BETKOTA'), ('fuboia', 'FuboIA'), ('wynnma', 'WynnMA'), ('mgm_natl_harbor_md', 'MGM Natl Harbor MD'), ('igt', 'IGT'), ('db_sportsbook_test', 'DB Sportsbook Test'), ('truebookies', 'Truebookies'), ('paradisewager', 'ParadiseWager'), ('pph_test', 'PPH Test'), ('4castersports', '4CasterSports'), ('amapola', 'Amapola'), ('betjet88', 'BetJet88'), ('shiba', 'Shiba'), ('prophet_exchange_nj', 'Prophet Exchange NJ'), ('3et', '3et'), ('sundaybets', 'SundayBets'), ('circaco', 'CircaCO'), ('gantest1', 'GANTest1'), ('gantest2', 'GANTest2'), ('circail', 'CircaIL'), ('ts_lambda', 'ts_lambda'), ('ts_lambda_stage', 'ts_lambda_stage'), ('donbest', 'DonBest'), ('bettorsden', 'BettorsDen')], max_length=50),
        ),
    ]
