# Generated by Django 5.2.3 on 2025-07-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_bet_bet_date_alter_bet_sportsbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
